using System.Globalization;

namespace StandaloneTrajectoryCalculator.Gui;

internal enum UiLanguage
{
    English,
    Russian
}

internal static class UiTextCatalog
{
    private static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>
    {
        ["app.title"] = "Solar System Transfer Planner",
        ["app.short_title"] = "Transfer Planner",
        ["language.english"] = "English",
        ["language.russian"] = "Русский",
        ["label.language"] = "Language",
        ["label.current_json"] = "Current JSON",
        ["action.single_template"] = "Single Template",
        ["action.porkchop_template"] = "Porkchop Template",
        ["action.open_json"] = "Open JSON",
        ["action.save_json"] = "Save JSON",
        ["action.run"] = "Run",
        ["action.rocket_builder"] = "AI Rocket Builder",
        ["card.transfer_schedule"] = "Transfer Schedule",
        ["card.porkchop_scan"] = "Porkchop Scan",
        ["field.trajectory"] = "Trajectory",
        ["field.aerobraking"] = "Use Aerobraking",
        ["group.parking_orbits"] = "Parking Orbits",
        ["group.output_files"] = "Output Files",
        ["group.selected_planet_data"] = "Selected Planet Data",
        ["group.origin_planet"] = "Origin Planet",
        ["group.destination_planet"] = "Destination Planet",
        ["group.written_files"] = "Written Files",
        ["tab.summary"] = "Summary",
        ["tab.delta_v_visual"] = "Delta-V Visual",
        ["tab.solar_system_view"] = "Solar System",
        ["tab.scenario_json"] = "Scenario JSON",
        ["tab.result_json"] = "Result JSON",
        ["field.origin_planet"] = "Origin planet",
        ["field.destination_planet"] = "Destination planet",
        ["field.mode"] = "Mode",
        ["field.long_way"] = "Long-way",
        ["field.single_departure"] = "Single departure UTC",
        ["field.single_travel_days"] = "Single travel days",
        ["field.window_start"] = "Window start UTC",
        ["field.window_end"] = "Window end UTC",
        ["field.travel_min_days"] = "Travel min days",
        ["field.travel_max_days"] = "Travel max days",
        ["field.departure_steps"] = "Departure steps",
        ["field.travel_steps"] = "Travel steps",
        ["field.departure_parking_orbit"] = "Departure parking orbit, km",
        ["field.arrival_mode"] = "Arrival mode",
        ["field.arrival_parking_orbit"] = "Arrival capture periapsis, km",
        ["field.arrival_aerobraking"] = "Use aerobraking",
        ["field.csv_output_path"] = "CSV output path",
        ["field.result_json_path"] = "Result JSON path",
        ["field.launch_enabled"] = "Mission start",
        ["field.launch_mode"] = "Calculation mode",
        ["field.launch_mass_kg"] = "Rocket initial mass, kg",
        ["field.launch_thrust_mn"] = "Rocket thrust, MN",
        ["field.launch_isp_sec"] = "Rocket ISP, sec",
        ["field.launch_latitude"] = "Launch latitude, deg",
        ["field.launch_longitude"] = "Launch longitude, deg",
        ["field.launch_inclination"] = "Target inclination, deg",
        ["group.launch_config"] = "Launch Configuration",
        ["option.launch_mode.quick"] = "Quick estimate (no data needed)",
        ["option.launch_mode.detailed"] = "Detailed simulation (needs rocket data)",
        ["option.mode.single"] = "single",
        ["option.mode.porkchop"] = "porkchop",
        ["option.long_way.auto"] = "auto",
        ["option.long_way.short"] = "short-way",
        ["option.long_way.long"] = "long-way",
        ["option.arrival.elliptic"] = "high-elliptic capture",
        ["option.arrival.circular"] = "circular capture",
        ["option.arrival.flyby"] = "flyby",
        ["option.arrival.ignore"] = "ignore arrival burn",
        ["info.title"] = "Solar System mode with built-in JPL data",
        ["info.body"] = "Prepared presets: Mercury through Neptune. Orbital series are tied to J2000 and mission times are entered in UTC, then converted to seconds since J2000 for the solver.",
        ["status.running"] = "Running calculation...",
        ["status.completed"] = "Calculation completed. Files written: {0}.",
        ["status.loaded"] = "Loaded scenario from {0}",
        ["status.saved"] = "Scenario saved to {0}",
        ["status.ready"] = "Ready",
        ["status.scenario_loaded"] = "Scenario loaded.",
        ["status.error"] = "Error: {0}",
        ["text.no_files_written"] = "No files were written.",
        ["text.no_result_json"] = "No result JSON file was written.",
        ["text.validation_error"] = "Validation error:",
        ["text.select_planet"] = "Select a planet.",
        ["text.yes"] = "yes",
        ["text.no"] = "no",
        ["text.planet_series_earth"] = "JPL Earth orbit series (EM-bary approximation)",
        ["text.planet_series_other"] = "JPL long-term orbit series",
        ["text.planet.mu"] = "mu",
        ["text.planet.radius"] = "radius",
        ["text.planet.soi"] = "SOI",
        ["text.planet.a"] = "a",
        ["text.planet.e"] = "e",
        ["text.planet.i"] = "i",
        ["text.planet.lan"] = "LAN",
        ["text.planet.arg_peri"] = "arg peri",
        ["text.planet.mj2000"] = "M@J2000",
        ["dialog.open_title"] = "Open scenario JSON",
        ["dialog.save_title"] = "Save scenario JSON",
        ["dialog.json_files"] = "JSON files (*.json)",
        ["dialog.all_files"] = "All files (*.*)",
        ["error.input_json_parse"] = "Input JSON could not be parsed.",
        ["error.same_planets"] = "Origin and destination planets must be different.",
        ["error.required"] = "{0} is required.",
        ["error.planet_not_found"] = "Planet '{0}' is not in the built-in Solar System catalog.",
        ["error.departure_orbit_order"] = "Departure orbit apoapsis must be greater than or equal to periapsis.",
        ["visual.empty_delta"] = "Run a calculation to see the minimum delta-v.",
        ["visual.empty_solar"] = "Run a calculation to see the departure geometry.",
        ["visual.delta.best_caption"] = "Best transfer from porkchop scan",
        ["visual.delta.single_caption"] = "Current transfer",
        ["visual.delta.total"] = "Total dV",
        ["visual.delta.ejection"] = "Ejection dV",
        ["visual.delta.insertion"] = "Insertion dV",
        ["visual.delta.departure"] = "Departure",
        ["visual.delta.travel"] = "Travel",
        ["visual.delta.phase"] = "Phase angle",
        ["visual.delta.grid"] = "Grid",
        ["visual.delta.departure_axis"] = "Departure date",
        ["visual.delta.travel_axis"] = "Travel days",
        ["visual.delta.legend_low"] = "Lower dV",
        ["visual.delta.legend_high"] = "Higher dV",
        ["visual.delta.best_point"] = "Best point",
        ["visual.delta.heatmap_title"] = "Delta-v map",
        ["visual.delta.breakdown_title"] = "Transfer delta-v breakdown",
        ["visual.solar.phase_angle"] = "Phase angle",
        ["visual.solar.long_way"] = "Long-way",
        ["visual.solar.origin_departure"] = "Origin at departure",
        ["visual.solar.destination_departure"] = "Destination at departure",
        ["visual.solar.destination_arrival"] = "Destination at arrival",
        ["visual.solar.transfer_path"] = "Transfer path",
        ["visual.solar.scale_note"] = "Orbit sizes are visually compressed so inner and outer planets fit in one view.",
        ["field.departure_orbit_periapsis"] = "Departure orbit periapsis, km",
        ["field.departure_orbit_apoapsis"] = "Departure orbit apoapsis, km",
        ["option.launch_profile.orbit"] = "start in parking orbit",
        ["option.launch_profile.surface"] = "launch from surface",
    };

    private static readonly IReadOnlyDictionary<string, string> Russian = new Dictionary<string, string>
    {
        ["app.title"] = "Планировщик перелетов по Солнечной системе",
        ["app.short_title"] = "Планировщик перелетов",
        ["language.english"] = "English",
        ["language.russian"] = "Русский",
        ["label.language"] = "Язык",
        ["label.current_json"] = "Текущий JSON",
        ["action.single_template"] = "Одиночный шаблон",
        ["action.porkchop_template"] = "Шаблон porkchop",
        ["action.open_json"] = "Открыть JSON",
        ["action.save_json"] = "Сохранить JSON",
        ["action.run"] = "Запустить",
        ["action.rocket_builder"] = "Ракетостроитель",
        ["card.transfer_schedule"] = "Расписание перелёта",
        ["card.porkchop_scan"] = "Сканирование porkchop",
        ["field.trajectory"] = "Траектория",
        ["field.aerobraking"] = "Использовать аэрозамедление",
        ["group.mission"] = "Миссия",
        ["group.parking_orbits"] = "Парковочные орбиты",
        ["group.output_files"] = "Файлы вывода",
        ["group.selected_planet_data"] = "Данные выбранных планет",
        ["group.origin_planet"] = "Планета отправления",
        ["group.destination_planet"] = "Планета назначения",
        ["group.written_files"] = "Созданные файлы",
        ["tab.summary"] = "Сводка",
        ["tab.delta_v_visual"] = "Визуализация dV",
        ["tab.solar_system_view"] = "Солнечная система",
        ["tab.scenario_json"] = "JSON сценария",
        ["tab.result_json"] = "JSON результата",
        ["field.origin_planet"] = "Планета отправления",
        ["field.destination_planet"] = "Планета назначения",
        ["field.mode"] = "Режим",
        ["field.long_way"] = "Траектория",
        ["field.single_departure"] = "Дата старта UTC",
        ["field.single_travel_days"] = "Длительность перелета, дни",
        ["field.window_start"] = "Начало окна UTC",
        ["field.window_end"] = "Конец окна UTC",
        ["field.travel_min_days"] = "Мин. длительность, дни",
        ["field.travel_max_days"] = "Макс. длительность, дни",
        ["field.departure_steps"] = "Шаги по старту",
        ["field.travel_steps"] = "Шаги по времени",
        ["field.departure_parking_orbit"] = "Стартовая орбита, км",
        ["field.arrival_mode"] = "Режим прибытия",
        ["field.arrival_parking_orbit"] = "Перицентр орбиты прибытия, км",
        ["field.arrival_aerobraking"] = "Использовать аэроторможение",
        ["field.csv_output_path"] = "Путь к CSV",
        ["field.result_json_path"] = "Путь к JSON результата",
        ["field.launch_enabled"] = "Старт миссии",
        ["field.launch_mode"] = "Режим расчета",
        ["field.launch_mass_kg"] = "Начальная масса ракеты, кг",
        ["field.launch_thrust_mn"] = "Тяга ракеты, МН",
        ["field.launch_isp_sec"] = "Удельный импульс, сек",
        ["field.launch_latitude"] = "Широта запуска, град",
        ["field.launch_longitude"] = "Долгота запуска, град",
        ["field.launch_inclination"] = "Целевой наклон, град",
        ["group.launch_config"] = "Конфигурация запуска",
        ["option.launch_mode.quick"] = "Быстрая оценка (без данных)",
        ["option.launch_mode.detailed"] = "Точная симуляция (нужны данные ракеты)",
        ["option.mode.single"] = "одиночный",
        ["option.mode.porkchop"] = "porkchop",
        ["option.long_way.auto"] = "авто",
        ["option.long_way.short"] = "короткий путь",
        ["option.long_way.long"] = "длинный путь",
        ["option.arrival.elliptic"] = "захват на высокую эллиптическую",
        ["option.arrival.circular"] = "круговой захват",
        ["option.arrival.flyby"] = "пролет",
        ["option.arrival.ignore"] = "игнорировать торможение",
        ["info.title"] = "Режим Солнечной системы со встроенными данными JPL",
        ["info.body"] = "Подготовлены пресеты от Меркурия до Нептуна. Орбитальные ряды привязаны к J2000, а время миссии вводится в UTC и затем переводится в секунды с эпохи J2000 для решателя.",
        ["status.running"] = "Выполняется расчет...",
        ["status.completed"] = "Расчет завершен. Создано файлов: {0}.",
        ["status.loaded"] = "Сценарий загружен из {0}",
        ["status.saved"] = "Сценарий сохранен в {0}",
        ["status.ready"] = "Готов",
        ["status.scenario_loaded"] = "Сценарий загружен.",
        ["status.error"] = "Ошибка: {0}",
        ["text.no_files_written"] = "Файлы не были созданы.",
        ["text.no_result_json"] = "Файл JSON с результатом не был создан.",
        ["text.validation_error"] = "Ошибка проверки:",
        ["text.select_planet"] = "Выбери планету.",
        ["text.yes"] = "да",
        ["text.no"] = "нет",
        ["text.planet_series_earth"] = "Серия орбиты Земли JPL (аппроксимация EM-bary)",
        ["text.planet_series_other"] = "Долгопериодическая орбитальная серия JPL",
        ["text.planet.mu"] = "mu",
        ["text.planet.radius"] = "радиус",
        ["text.planet.soi"] = "СОИ",
        ["text.planet.a"] = "a",
        ["text.planet.e"] = "e",
        ["text.planet.i"] = "i",
        ["text.planet.lan"] = "ДВУ",
        ["text.planet.arg_peri"] = "арг. перицентра",
        ["text.planet.mj2000"] = "M@J2000",
        ["dialog.open_title"] = "Открыть JSON сценария",
        ["dialog.save_title"] = "Сохранить JSON сценария",
        ["dialog.json_files"] = "Файлы JSON (*.json)",
        ["dialog.all_files"] = "Все файлы (*.*)",
        ["error.input_json_parse"] = "Не удалось разобрать входной JSON.",
        ["error.same_planets"] = "Планета отправления и назначения должны отличаться.",
        ["error.required"] = "Поле \"{0}\" обязательно.",
        ["error.planet_not_found"] = "Планета \"{0}\" отсутствует во встроенном каталоге Солнечной системы.",
        ["error.departure_orbit_order"] = "Апоцентр стартовой орбиты не может быть меньше перицентра.",
        ["visual.empty_delta"] = "Запусти расчет, чтобы увидеть минимум delta-v.",
        ["visual.empty_solar"] = "Запусти расчет, чтобы увидеть геометрию старта.",
        ["visual.delta.best_caption"] = "Лучший перелет из porkchop-скана",
        ["visual.delta.single_caption"] = "Текущий перелет",
        ["visual.delta.total"] = "Общее dV",
        ["visual.delta.ejection"] = "dV старта",
        ["visual.delta.insertion"] = "dV захвата",
        ["visual.delta.departure"] = "Старт",
        ["visual.delta.travel"] = "Перелет",
        ["visual.delta.phase"] = "Фазовый угол",
        ["visual.delta.grid"] = "Сетка",
        ["visual.delta.departure_axis"] = "Дата старта",
        ["visual.delta.travel_axis"] = "Дни перелета",
        ["visual.delta.legend_low"] = "Меньше dV",
        ["visual.delta.legend_high"] = "Больше dV",
        ["visual.delta.best_point"] = "Лучшая точка",
        ["visual.delta.heatmap_title"] = "Карта delta-v",
        ["visual.delta.breakdown_title"] = "Разбивка delta-v перелета",
        ["visual.solar.phase_angle"] = "Фазовый угол",
        ["visual.solar.long_way"] = "Длинный путь",
        ["visual.solar.origin_departure"] = "Планета старта",
        ["visual.solar.destination_departure"] = "Планета назначения на старте",
        ["visual.solar.destination_arrival"] = "Планета назначения на прилете",
        ["visual.solar.transfer_path"] = "Траектория перелета",
        ["visual.solar.scale_note"] = "Размеры орбит визуально сжаты, чтобы внутренние и внешние планеты поместились в одном окне.",
        ["field.departure_orbit_periapsis"] = "Перицентр стартовой орбиты, км",
        ["field.departure_orbit_apoapsis"] = "Апоцентр стартовой орбиты, км",
        ["option.launch_profile.orbit"] = "Старт с орбиты",
        ["option.launch_profile.surface"] = "Запуск с поверхности",
    };

    public static UiLanguage DetectInitialLanguage()
    {
        return CultureInfo.CurrentUICulture.TwoLetterISOLanguageName.Equals("ru", StringComparison.OrdinalIgnoreCase)
            ? UiLanguage.Russian
            : UiLanguage.English;
    }

    public static string Get(UiLanguage language, string key)
    {
        var map = language == UiLanguage.Russian ? Russian : English;
        return map.TryGetValue(key, out var value) ? value : key;
    }

    public static string Format(UiLanguage language, string key, params object[] args)
    {
        return string.Format(Get(language, key), args);
    }
}
